POST https://netzwelt-devtest.azurewebsites.net/Account/SignIn
content-type: application/json

{
  "username": "foo",
  "password": "bar"
}

###

GET https://netzwelt-devtest.azurewebsites.net/Territories/All

###

POST http://localhost:8000/api/login
content-type: application/json

{
  "username": "foo",
  "password": "bar"
}

###
POST http://localhost:8000/api/login
content-type: application/json

{
  "username": "foooooo",
  "password": "barrrrr"
}

###
GET http://localhost:8000/api/territories